apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: civicpulse

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
        - name: auth-service
          image: illuriganesh123/civicpulse-auth-service:1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8081

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://auth-mysql:3306/civicpulse_auth_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: SPRING_DATASOURCE_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: JWT_SECRET

            - name: NOTIFICATION_SERVICE_URL
              value: http://notification-service:8083