apiVersion: v1
kind: Service
metadata:
  name: notification-mysql
  namespace: civicpulse

spec:
  selector:
    app: notification-mysql

  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

  type: ClusterIP