apiVersion: v1
kind: Service

metadata:
  name: grievance-service
  namespace: civicpulse

spec:
  selector:
    app: grievance-service

  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082

  type: ClusterIP